blank_issues_enabled: false
contact_links:
  - name: MotionPlus User Questions
    url: https://github.com/Motion-Project/motionplus/discussions
    about: Please ask and answer questions here.
  - name: MotionPlus Enhancements
    url: https://github.com/Motion-Project/motionplus/discussions
    about: Please use the discussions page and tag as an enhancement request.
